version: "3.8"

services:
  quarkus-service:
    container_name: quarkus_container
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - quarkus
    links:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: plic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - quarkus
    restart: unless-stopped

networks:
  quarkus:
    driver: bridge

volumes:
  postgres: