version: "3.8"

services:
  quarkus-service:
    container_name: quarkus_container
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - quarkus
    environment:
      - MINIO_SERVER_ACCESS_KEY=minioadmin
      - MINIO_SERVER_SECRET_KEY=minioadmin
    links:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: plic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - quarkus
    restart: unless-stopped

  minio:
    container_name: minio_container
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - minio:/data
    networks:
      - quarkus

networks:
  quarkus:
    driver: bridge

volumes:
  minio:
  postgres: